### ISSUE TITLE
Redux include in functions.php

### ISSUE THREAD

**Issue by jetonr** [evertiro/historical-redux2#1]
replace 
get_template_part('redux', 'options');
to
get_template_part('redux', 'framework');

because the file name is redux-framework.php

**Comment by evertiro** [comment]
Valid point but perhaps I should rewrite that section. redux-framework.php is just a pseudo plugin I use for testing purposes and to show how to include the panel.

**Comment by jetonr** [comment]
Ok. I am testing now with my theme everything seems perfect so far!

**Comment by evertiro** [comment]
Fixed docs issue
