### ISSUE TITLE
How can I contribute?

### ISSUE THREAD

**Issue by hittheroadjack** [evertiro/historical-redux2#100]
Few days ago, I found this fantastic network while googleing around NHP. I have integrated it in Shibashake's plugin template for my own use.
Now I have coded some custom fields - a slider (min/max) and an accordion field with textareas in the content. 
Is there interest in those?
It seems, that I can do nothing besides 'adding issues'. Do I need an extra permission to be able to add a pull request? Or how else can I contribute?
BTW, I am German - in case there is some need for i18n. I have done it for SimplePress, BackupBuddy, SlideDeck2, subscribe2 and some other WP plugins.

**Comment by evertiro** [comment]
I'm all for adding functionality! Nothing is required to add a pull request, [here](https://help.github.com/articles/using-pull-requests) is an article on Github pull requests if you're having issues. Additionally... take a look at the open issues requests and see if you have any thoughts on how to best resolve them! Welcome to the Redux family!
