### ISSUE TITLE
 Google web fonts api !

### ISSUE THREAD

**Issue by liebre** [evertiro/historical-redux2#108]
hey  i have small problem  to setup  Google web fonts api !! the option is working but i can not see any effect at my "font-family" when i add link href='http://fonts.googleapis.com/css?family=<?php echo $options['google_webfonts_demo']; ?>' rel='stylesheet' type='text/css' /> to my header.php , and it working when i add for example link href='http://fonts.googleapis.com/css?family=Viga' rel='stylesheet' type='text/css' />
so ?!

**Comment by hectorgarrofe** [comment]
Take a look at my Issue: https://github.com/ghost1227/Redux-Framework/issues/81

Maybe it will help you. ;)

**Comment by liebre** [comment]
thx i saw your issue before i submit my issue , the all steps is working , just i cannot get the font source from google ?! i donot know are there is problem at my code ?!  or what ?! and also what meaning with api ?! is it google development api ?! or just at my code .....link href='http://fonts.googleapis.com/css?family=<?php echo $options['google_webfonts_demo']; ?>' ?!!

**Comment by liebre** [comment]
Solved :+1:
