### ISSUE TITLE
Upload not working

### ISSUE THREAD

**Issue by bimaljr** [evertiro/historical-redux2#11]
Hello,

I tried both "master" and "stable" but the Upload is not working. It gives error:

```
Uncaught ReferenceError: formfield is not defined 
```

I am using latest Wordpress 3.5 and default setup. This is fresh Wordpress. No-pluign or theme installed.

I am developing a theme and want to use the framework so I am trying it.

Is there any patch for this?

**Comment by alexpos** [comment]
With the famous words it works here, this might help: a child-theme to test redux options, could you test if this works? It might help to debug the problem.

[Twenty-twelve-redux](https://github.com/plovs/twentytwelve-redux) - child-theme to test the framework

**Comment by denis0706** [comment]
Hello.

I have the same problem as bimaljr.
The main issue i think  is that field_upload.js script can't access global vars and can't access vars from wp_localize_script, it seems that  wp_localize_script (\admin\options\fields\upload\field_upload.php) do nothing. trying to figure out why is it happening.

**Comment by alexpos** [comment]
please do, did a clean checkout of the [testing theme](https://github.com/plovs/twentytwelve-redux) + [Redux-Framework](https://github.com/ghost1227/Redux-Framework)  and in my install it still works. Difficult to  fix something without it visible breakage :-( As soon as you have something useful we'll be all over it ... we're watching this thread (you can also use [plovs@twitter](http://twitter.com/plovs))

**Comment by evertiro** [comment]
It's working fine for me too :( So annoying when things _sometimes_ break.

**Comment by denis0706** [comment]
The problem with wp_localize_script was mismatch in names, i have  pulled request already.
Problem with javascript is cause using 'strict mode'. Variables must be declared before they can be assigned while using 'strict mode'. Now its work fine.
Reason, why its working for you, guys, is strict mode isn't applyed somehow or variables are declared somewhere outer of field_upload.js.

**Comment by alexpos** [comment]
excellent!

**Comment by denis0706** [comment]
Also, some ad remove browser plugins can block popup upload window. 
In my case Opera AdBlock extension hides popup window. 
I will try to figure out why AdBlock recognizes popup as ad and check, if it happens in other browsers with such extensions.

**Comment by alexpos** [comment]
chrome adblock does not block it, btw

**Comment by evertiro** [comment]
No problems on Chrome or Firefox with any of the ad blockers I've tested. I never thought to test with Opera though... Good thing we have a user around who did!

**Comment by evertiro** [comment]
Pull request was merged.. Not sure I never closed the bug.
