### ISSUE TITLE
Redux-Framework - Few questions

### ISSUE THREAD

**Issue by matriarmch** [evertiro/historical-redux2#110]
Hi guys,

I have some questions about how redux-framework works.
1. How i can send my color choice to css file or background image to css class.
2. It is possible to make color settings like this:
   |-Menu Select
   |----Black
   |----White
   When i click Black from menu-select all pickers on setting-page will change to #000.
3. Third question is about array('type' => 'checkbox',) with switcher.
   How i can use that array with "elseif/else if" function. If switcher=on then show code, if switcher=off hide code.

I think its realy nice framework but You need to explain more how to use it in more advanced solutions becouse as we know we don't need to use any framework to display what we write in text-field only.
Thanks for any reply.
chalenski

**Comment by djevrek** [comment]
you can do like this 

``` html
<style>
body {
background: #
    <?php 
$test = $options['color-selector'];
echo $test; ?>;
}
</style>
```

in your html. 

For your first question.

**Comment by matriarmch** [comment]
Djevrek, first thanks for your reply,  about your code, its natural that you can display your color like this in php file but  when i want send it to css file or registry new css file with framework variables.

**Comment by djevrek** [comment]
Easy as this http://net.tutsplus.com/tutorials/php/supercharge-your-css-with-php-under-the-hood/

**Comment by evertiro** [comment]
Djevrek is correct in terms of the first question. I'm not sure I understand the second question you are asking... can you explain what your issue is a bit further? As for the third option... do you mean you want to have an elseif condition actually IN the settings page? If so, there are two functions, checkbox_hide_all and checkbox_hide_below, which can accomplish this.

**Comment by matriarmch** [comment]
2nd question, for example, I have 10 color pickers on setting page and 1 menu select. All color pickers have set #000 color when in menu select is selected black, and when i change in that menu to white all color pickers will change color from #000 to #fff. I ask about it when i will want to make some color shemes of my theme.

3rd question is when i want to do something like that. Make in setting page switcher for "show header message ?" and switch yes/no, and use elseif condition in theme:

if ( switcher = yes ) { show code for for header message } elseif ( switcher = no ) { break; };

**Comment by matriarmch** [comment]
Ok, anyone ?

@ghost1227 I think dont understand my problem in 3rd question, its not about how to hide some options in redux-panel , question is about how to hide some options in theme file, example header.php by using redux-panel.

When i click Switch Option on/off in redux-panel "on" show some code in header.php or if switcher is "off" hide this code.

2nd question is about creating color shemes of my theme. First solution is to make css file by php like this using color pickers from redux. But that question is about something different. Is it possible to make packs of color pickers and change it to another colors by menu select. When i have menu select with two variables like "black" and "white", when i chosee "black" all color pickers change colors to #000, when i chosee "white" in same menu select all color pickers will change to #fff.

**Comment by evertiro** [comment]
Sorry, I've been a bit busy lately and forgot about this issue. Are you still having issues?

**Comment by dovy** [comment]
@chalenski @djevrek Take a look at these two issues for answers to your questions:
Dynamic CSS generating: https://github.com/ghost1227/Redux-Framework/issues/152
Fold Argument - Linking/Hiding Items by Value - https://github.com/ghost1227/Redux-Framework/issues/154

They're both coming in 3.0.  :)
