### ISSUE TITLE
Used in theme and plugin, get Cannot redeclare class Redux_Options error

### ISSUE THREAD

**Issue by trentb2** [evertiro/historical-redux2#113]
If I have the Redux-Framework installed in both a theme and plugin at the same time, I get a Cannot redeclare class Redux_Options error. What is the best way to use this as options for plugin and option for theme at the same time. Thanks, this is the best options framework I have come across.

**Comment by evertiro** [comment]
Replace all instances of `Redux_Options` with a name of your choice, and do the same for `redux-opts` and `Redux_TEXT_DOMAIN`. Easiest way would be just replacing redux with yourpluginname in all three. I generally make a habit of doing this anyway... just to be safe.
