### ISSUE TITLE
Error when there are no options

### ISSUE THREAD

**Issue by ghost** [evertiro/historical-redux2#116]
Hi there,

I saw this message in the Tag Select Option section:

Warning: Invalid argument supplied for foreach() in C:\wamp\www\devbp\wp-content\themes\buildpress\library\admin\options\redux\options\fields\select\field_select.php on line 32

I figured it might relate to the fact that I'm working on a new, local install and don't have any tags.  So I created a tag, saved the post - and sure enough the message went away.

I then noticed down below a similar message for Menu Location Select Option:  

Warning: Invalid argument supplied for foreach() in C:\wamp\www\devbp\wp-content\themes\buildpress\library\admin\options\redux\options\fields\select\field_select.php on line 32

So, I registered a menu option - and once again the warning went away.

Perhaps a solution would be to check first if there are tags or registered menus and only then run the code - I imagine that way one won't see a warning in that situation.

**Comment by evertiro** [comment]
Definitely a problem! I just noticed that a few days ago myself, and I'm working on a fix for it (as my job permits time that is)

**Comment by ghost** [comment]
Great, glad to hear that you are working on it.

**Comment by dovy** [comment]
Resolved in 3.0.
