### ISSUE TITLE
Is It Possible Not to Show the Theme Information Tab?

### ISSUE THREAD

**Issue by ghost** [evertiro/historical-redux2#117]
Hi there,

Is it possible not to show the Theme Information tab?  If so, how do I disable it? 

Thanks,

Moshe

**Comment by evertiro** [comment]
Simple! Just remove [this](https://github.com/ghost1227/Redux-Framework/blob/master/options.php#L766-L780) from options.php!

**Comment by ghost** [comment]
Great - thanks.
