### ISSUE TITLE
Bug on first setup: "undefined index: icon_type"

### ISSUE THREAD

**Issue by darth90rs** [evertiro/historical-redux2#118]
Hi there! I found this bug just after setting up the framework for my theme.
When in wp-admin->Options, on the left sidebar of the framework panel, for each section, before the icon and the title of the menu item, I get this warning:

<i>Notice: Undefined index: icon_type in /htdocs/public/wp/wp-content/themes/tesi/admin/options/defaults.php on line 643</i>

This is for the first 5 elements, then the message changes the line number: 660, 674 and 688.
Though the icon is displaying well!

I tryed to get rid of it, and found a way:
In options.php, on line 78 I added the following:

<i>$args['icon_type'] = '';</i>

This seems to fix the bug, because after doing so the warning message doesn't appear in the backend.
Hope this can help!
Keep up the good work!

Riccardo

**Comment by evertiro** [comment]
Looks like I missed a check in the defaults file! I'll get that added shortly. Thanks for catching it!

**Comment by evertiro** [comment]
Closing as a duplicate, please post further updates to #136
