### ISSUE TITLE
Fatal error: Call to undefined function wp_reset_vars() 

### ISSUE THREAD

**Issue by iftieaq007** [evertiro/historical-redux2#119]
I got an error message Fatal error: Call to undefined function wp_reset_vars() in \htdocs\crystal\wp-admin\options.php on line 25

**Comment by evertiro** [comment]
Can you elaborate? Does this happen in a certain situation? Or constantly?

**Comment by edirpedro** [comment]
I got this error too, it's occurs when you install the framework on theme root, when you do this you have a conflict with the file "options.php" from the framework and the "/wp-admin/options.php".

Simply change the name "options.php" to "redux.php" and voila.

**Comment by dovy** [comment]
Resolved in 3.0 already.

**Comment by adrian7** [comment]
I encountered this issue again, in 5.4. The steps I took:

 - create a child theme for `twentytwenty`
 - create `childtheme/functions.php`
 - create `childtheme/options.php` 
 - `include_once 'options.php';` in functions.php
