### ISSUE TITLE
Ajax with options saving system

### ISSUE THREAD

**Issue by rajuahmmed** [evertiro/historical-redux2#121]
We need Ajax saving system, when we will press on save it will be save with Ajax.

**Comment by dovy** [comment]
@rajuahmmed I come from SMOF where that works great. It could be good, but it's not a huge priority as of yet. I will eventually get it in. We've got so much we're changing with 3.0, it's on the back burner.  But, I do have the code. It's just a matter of doing it.

**Comment by dovy** [comment]
It's also a little difficult because the Wordpress settings API doesn't support that. So we'd have to bypass it, and then return the values... Could be messy.
