### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by iftieaq007** [evertiro/historical-redux2#122]
Can I use Redux Framework for commercial work? Thanks.

**Comment by evertiro** [comment]
Yes! In fact, some people already are! Just lemme know so I can check it out when you release it... I love seeing how people use my work :smile:

**Comment by burbridgeconsulting** [comment]
[aside] Gotta say, this framework is awesome, and should be known about. I plan to use it in my next themes and plugins.

**Comment by evertiro** [comment]
Thanks! Love getting positive reviews like that!
