### ISSUE TITLE
REQ Repeater Field

### ISSUE THREAD

**Issue by bluehiveinteractive** [evertiro/historical-redux2#123]
I'm looking to see if anyone has attempted to integrate a repeater field into the framework. Basically I'm looking for something like this:

I create a new repeater field called: Social Media
Within the repeater field is a sub-set of fields like the following:
Social Media Icon (this would be an upload/image field)
Social Media Profile URL (this would be a standard text field)

Then there would be a simple "+" plus button to add another social media account to the site.  If I wanted to have facebook, twitter and pinterest I would plus in 3 repeated fields. Each containing the field for the icon upload and the text field for the profile url.

I've been using Advanced Custom Fields ( http://www.advancedcustomfields.com/ ) repeater fields add-on ( http://www.advancedcustomfields.com/add-ons/repeater-field/ ) for this very reason for client sites, but for commercial theme releases I cannot embed ACF into it and will need to use the Redux Framework.

I appreciate your input/thoughts on this.

**Comment by burbridgeconsulting** [comment]
This is a great idea. Elliot Condon's implementation in ACF is beautiful and could be used as a model.

His DB implementation is very simple. If you create a field called Address, he creates a field meta_key of address. If you made address into a repeater field, with an actual field (able to give a specific value to) of type, then in the DB, the first value would have a meta_key of address_type_0. The next one, address_type_1, and so on.

This method seems a little bit breakable in a way, but that is how he does it. (I.e., why not prefix it all with 'acf_'.).

I'm not saying I _would_ be able to find the time to help with this, but I am interested in the _idea_ of helping ;-)

**Comment by bhi-archive** [comment]
I am really not adept enough to take this on myself. But I am glad I'm not the only one who sees the value in this. If there is anyone here is has the chops to take this addition on, much gratitude would come your way :-)

**Comment by towfiqi** [comment]
:+1:  you guys should look into SMOF's sllider repeater field:
https://github.com/syamilmj/Options-Framework/blob/master/admin/classes/class.options_machine.php

**Comment by dovy** [comment]
@towfiqi @bluehiveinteractive @burbridgeconsulting 

Would you want to just mimic SMOF? Or how is ACF's? Can I please get a URL to ACF?

We're willing to implement anything that makes sense.

If we're talking about making it more dynamic maybe there's a way I could make it so fields could be linked. I don't know though...

**Comment by ghost** [comment]
http://www.advancedcustomfields.com/

**Comment by dovy** [comment]
Umm, wow. Just wow. Fantastic stuff. Going to have to look at this codebase a bit. ;)

**Comment by towfiqi** [comment]
Admin Page Class(My Options Panel) also has a repeater function. You could also take a look at it:
https://github.com/bainternet/Admin-Page-Class/blob/master/admin-page-class/admin-page-class.php

I wish I had extensive knowledge on php. I tried looking into it myself, but couldn't figure out how to implement this to Redux. :/

**Comment by dovy** [comment]
I know how to make a repeater class, but I'd love to let you embed any field Redux had inside a repeater. Just thinking of how to make that happen. Hah.

**Comment by dovy** [comment]
Umm, well that was a crap-load easier than I thought it would be... Haha. It looks like I can do it. Man, I love this codebase.

Forthcoming, I can make a repeater class where you can set any number of fields within it. Pretty cool eigh?

**Comment by towfiqi** [comment]
lovely!!!! :) let us know when we can expect the new version with the repeater functionality. Thanks!

**Comment by dovy** [comment]
Maybe not as easy as I thought. I can get it to display, but I have to do some work in the validator. Hmm. Not sure this will make 3.0. Maybe 3.1...

**Comment by towfiqi** [comment]
Great! Keep up the good work! :)

**Comment by bhi-archive** [comment]
Great! I appreciate you looking into this. Its way over my head. Thanks
again.

_Chad Warren_
_Bluehive Interactive_
p. 412-467-6716
e. chad@bluehiveinteractive.com
w. http://www.bluehiveinteractive.com

**Comment by dovy** [comment]
This will require a complete change of how IDs and Names are set. Not horrible, but will take some time. Added as a feature request on the new repo.

**Comment by web-caos** [comment]
Edit:
Didn't read well :)
Anyway isn't hard to do, the problem would be more for display it than for store informations...

**Comment by rustanacexd** [comment]
any update on this?
