### ISSUE TITLE
Question ' How to show multi checkbox values, seperated or together ? ' 

### ISSUE THREAD

**Issue by LaurensWind** [evertiro/historical-redux2#124]
I'm a rookie in PHP, i hope you guys could give me some advise.

Here is the code :

array(
'id' => 'multi_checkbox_demo',
'type' => 'multi_checkbox',
'title' => __('Multi Checkbox Option', Redux_TEXT_DOMAIN), 
'sub_desc' => __('No validation can be done on this field type', Redux_TEXT_DOMAIN),
'desc' => __('This is the description field, again good for additional info.', Redux_TEXT_DOMAIN),
'options' => array('1' => 'Opt 1', '2' => 'Opt 2', '3' => 'Opt 3'), // Must provide key => value pairs for multi checkbox options
'std' => array('1' => '1', '2' => '2', '3' => '3') // See how std has changed? You also dont need to specify opts that are 0.
),

For example when i want to display 'Radio' values i use

<?php if ( 1 == $options['radio_demo']) { ?>
One
<?php } ?>

<?php if ( 2 == $options['radio_demo']) { ?>
Two
<?php } ?>

<?php if ( 3 == $options['radio_demo']) { ?>
Three
<?php } ?>

This does not work for the multi checkbox. On every check it is refering to 1.

How can i show the mutli checkbox values ? seperated or all together when they are checked ?

Greetz,

**Comment by evertiro** [comment]
Sorry for the delay. Checkboxes are a nested array. Try this:

`echo $options['multi_checkbox_demo'][1];`
