### ISSUE TITLE
Invalid argument supplied foreach()

### ISSUE THREAD

**Issue by jakelisby** [evertiro/historical-redux2#125]
I'm getting this error in my PHP logs when I load the options page. It fires 6 times in a row. Any tips on how to resolve this?

PHP Warning:  Invalid argument supplied for foreach() in /Users/jakelisby/Sites/ssekodesigns.lc/wp-content/themes/ssekoDesigns/includes/options/fields/select/field_select.php on line 32

**Comment by evertiro** [comment]
Yep. I missed a common check in a few of the field types. I've been slowly fixing them as I find them. It shouldn't affect usability, just throw that notice on occasion. Feel free to patch it, or I'll get to it shortly!

**Comment by evertiro** [comment]
Closing as a duplicate, please post further updates to #136
