### ISSUE TITLE
Undefined index notices for selects

### ISSUE THREAD

**Issue by Protohominid** [evertiro/historical-redux2#128]
I have my local dev sites set to show php notices and errors, and when I go to a Redux Options tab with select menu options, there are php notices all over the place. It only seems to be on the select menus. Here's an example:

Notice: Undefined index: multiselect in /Users/shawn/.../content/themes/sbgd-boilerplate/options/fields/select/field_select.php on line 26

I know these are only notices and can probably just be ignored, but I'm wondering why they are showing up and if there's a fix.

**Comment by evertiro** [comment]
Yep. I missed a common check in a few of the field types. I've been slowly fixing them as I find them. It shouldn't affect usability, just throw that notice on occasion. Feel free to patch it, or I'll get to it shortly!

**Comment by evertiro** [comment]
Closing as a duplicate, please post further updates to #136
