### ISSUE TITLE
Localize google fonts option

### ISSUE THREAD

**Issue by Deviantkool** [evertiro/historical-redux2#129]
Rather than an api_key and loading google fonts from google. Could you please assist with a similar option but enable us to load our own font.css from our theme folder. An please add a FONT Weight; FONT Style. The A+ and A- is great along with the preview. Really need this option.

**Comment by evertiro** [comment]
Can you elaborate? I'm not sure I understand what you're getting at...

**Comment by Deviantkool** [comment]
Never mind that option I found something more interesting....OK but what i was trying to say is if the JavaScript file could be modify for your local custom font.css file. Say for example i want to add my own Font which can be 4 or 5 fonts cause when your building a tight layout website you want to ensure that font-size are exact and responsive. But there is a easier way.

**Comment by dovy** [comment]
@Deviantkool With the new typography module forthcoming you can define your own font-families or use the defaults.  ;)

**Comment by Deviantkool** [comment]
Now that would be great because I like the Google font option. Not necessarily all the fonts just the structure of the option.
