### ISSUE TITLE
Raw HTML option displays outside of table

### ISSUE THREAD

**Issue by mgmartel** [evertiro/historical-redux2#132]
First of all: this framework is **awesome**!

tl,dr: Raw_html is outputted above all the other options.

The raw_html option is now outputted in a div after closing the table cell and row since commit c9d2659b7da4659707c8fa8972261a16a056d1fe (March 14th). However, this puts the div _before_ the whole table (tested in Chromium 28 and FF 21), instead of on its rightful place..

The old solution (closing the table before the div and creating a new table after the raw html has outputted) seems to work fine (though maybe not the most elegant). Why was this changed?

**Comment by evertiro** [comment]
I've noticed this as well... It will be reverted in the next version.

**Comment by evertiro** [comment]
Reverted... but I'm still not happy with it. Breaking the table forces some odd spacing issues on us.
