### ISSUE TITLE
PHP Notice:  Undefined variable: args

### ISSUE THREAD

**Issue by mindspins** [evertiro/historical-redux2#133]
When installing the options panel and visiting the default pages I get the following notices:

PHP Notice:  Undefined variable: args in options\fields\menu_select\field_menu_select.php on line 17

PHP Notice:  Undefined index: args in options\fields\post_type_select\field_post_type_select.php on line 17

PHP Notice:  Undefined index: args in
options\fields\post_type_multi_select\field_post_type_multi_select.php on line 17

Over all I must say... brilliant work!

**Comment by evertiro** [comment]
Yep. I missed a common check in a few of the field types. I've been slowly fixing them as I find them. It shouldn't affect usability, just throw that notice on occasion. Feel free to patch it, or I'll get to it shortly!

**Comment by evertiro** [comment]
Closing as a duplicate, please post further updates to #136
