### ISSUE TITLE
select_hide_below field

### ISSUE THREAD

**Issue by PearlWebStudio** [evertiro/historical-redux2#134]
Is there a possibility to hide and show specific arrays with select_hide_below field?

example; 
select option1 => hide next array 1 and 4, show next array 2 and 3
select option2 => hide next array 2, 3 and 4, show array 1
select option3 => hide next array 1, 2 and 3, show array 4

and how to use select_hide_below field inside another select_hide_below field?

**Comment by evertiro** [comment]
I've honestly never considered using a recursed select_hide_below field. I'm not even sure it's possible given the current setup. I'll definitely look into making it work if it doesn't though!

**Comment by cyberwani** [comment]
+1

**Comment by cyberwani** [comment]
I was created a same field-type in NHP before.

**Comment by lumberman** [comment]
It will be huge improvement usability-wise.

**Comment by dovy** [comment]
@PearlWebStudio @cyberwani @pavot You will want to look and comment here: https://github.com/ghost1227/Redux-Framework/issues/154

It's the new fold argument available to each field in 3.0.

:)
