### ISSUE TITLE
i don't understand what i am doing wrong?

### ISSUE THREAD

**Issue by foxpcteam** [evertiro/historical-redux2#135]
Hello,
i have problem to show/print some value.

i have include in functions.php  require_once('admin/options.php');
i have change in options.php the name to my theme
args['opt_name'] = 'my theme';

in admin section i have upload image for the array i give 
'id' => 'upload_logo',

when i try to print this image in my header.php it does not showing anything

i try 

<?php echo $options['upload_logo']; ?>

echo $options[''upload_logo'];

and many other way to print but none of them working...

someone please help my to print all the values i need to show in the front end to users

Thanks

**Comment by foxpcteam** [comment]
some one?

**Comment by evertiro** [comment]
Have you defined a global for the options array?

**Comment by foxpcteam** [comment]
Hello ghost,
i have add in functions.php $TEST=get_option('test1');
test1 is the name of my theme.
now for global where i need to write it?  

thanks

**Comment by evertiro** [comment]
it should be `global $TEST=get_option('test1');`, or you need to be defining $TEST as a global earlier in the script.
