### ISSUE TITLE
An unlimited content option. Unlike post but can be used on pages

### ISSUE THREAD

**Issue by Deviantkool** [evertiro/historical-redux2#142]
Just like the multitext option i made an attempt and failed. I was trying to combine a text option for a title; An upload option field for an image; An a text area style for short-codes to add any amount of text.
Now all of this is one option then you can add more( unlimited ) or delete what you have. Anyone can do this.

**Comment by evertiro** [comment]
What would the point of this be? We already have posts and pages as primary content types, and plugins exist to display post content on pages and vice versa...

**Comment by Deviantkool** [comment]
OK first you want to control multiple text and images without writing a post or a custom post-type. This idea can be ideal for a slider on homepage, non-post-type content withing a page, the ability to sort the content how you want it to be, it can also be use to add extra form fields when edited, multiple clients with their titles and links. It can be used multiple times in the options.php. 

I created a custom post-type for a slider; yes it works well but i want multiple sliders for different pages and God knows i don't want so much custom post-type.

**Comment by evertiro** [comment]
Not sure I feel that the idea of a 'page builder' should be included in core, but if all goes the way I expect it to, V3 will support extensions, and this could easily be built as an extension.

**Comment by Deviantkool** [comment]
It's not really a page builder we looking for its just a normal slider option thats all. Am sure users will find it useful

**Comment by dovy** [comment]
@Deviantkool 3.0 has a slider built in. Check out: http://demo.reduxframework.com/wp-admin/admin.php?page=redux_options   to see an example.

You should have all you need and more.
