### ISSUE TITLE
Possible to group together fields for "checkbox_hide_below"?

### ISSUE THREAD

**Issue by fierceangel** [evertiro/historical-redux2#144]
Is it possible to use "checkbox_hide_below" to reveal more than one field when checked? Unless I'm mistaken it only reveals the first field below it, but for my options panel I would like multiple fields revealed in one click.

**Comment by peter-nl** [comment]
You can use 'checkbox_hide_below' together with 'next_to_hide' => '9'.
Ref [ pull 112](https://github.com/ghost1227/Redux-Framework/pull/112).

**Comment by evertiro** [comment]
The checkbox_hide_below might be getting phased out in favor of a complete conditional system allowing ANY field to be conditionally shown depending on the value of ANY other field.

**Comment by lumberman** [comment]
I'd love to see more complex login for "checkbox_hide_below" and 'select_hide_below'. As theme designers we can make it easier for users to manage settings.

**Comment by evertiro** [comment]
Check out folding in the v3.0.0 release coming early next week!

**Comment by dovy** [comment]
@fierceangel @peter-nl @pavot Please look here: https://github.com/ghost1227/Redux-Framework/issues/154

I think you'll find that post VASTLY interesting.
