### ISSUE TITLE
New Wordpress skin parented from windows 8 android OS

### ISSUE THREAD

**Issue by Deviantkool** [evertiro/historical-redux2#145]
Have a new skin working on to say to the developers of WordPress to dominate the market. I don't see a sign up form at wp.org. Any suggestions?

**Comment by evertiro** [comment]
I'm not sure I understand the question... What are you trying to do?

**Comment by Deviantkool** [comment]
I am changing wordpress skin

**Comment by Deviantkool** [comment]
It's a new WordPress design for the cms. I am currently working on it. After i competed the design i am going to distribute the illustrator files to the developers. The old look isn't as pleasing as it should be.

**Comment by evertiro** [comment]
Not sure what this has to do with Redux, but it is 100% skinnable, just override the CSS!

**Comment by Deviantkool** [comment]
Well it has a lot to do with it in terms of design. Your framework looks great but WordPress doesn't. I don't want to keep it all to myself. I want all the wp users to experience the new look plus Twenty fourteen theme matches it perfectly. I just want to get it to the developers of WordPress. No PSD just AI files. Plus if it's from the developers of Redux then that means more traffic etc...
