### ISSUE TITLE
Presets Button...question

### ISSUE THREAD

**Issue by corradomatt** [evertiro/historical-redux2#147]
Is there a built in way to create a "presets" button of sorts. I'm thinking that with 1 click we can set multiple fields to have preset values....

I know that this can be done with import/export relatively easy...but it might be nice to offer preset styles for theme options. Some users can get scared by the import/export process.

**Comment by evertiro** [comment]
Interesting idea... won't likely make it into 3.0.0, but I can see adding it in the future!

**Comment by evertiro** [comment]
I take it back! Thanks to the merge with Simple Options, we now have presets in 3.0.0!
