### ISSUE TITLE
Tab hover issue when using MP6 plugin

### ISSUE THREAD

**Issue by Tidal-Wave** [evertiro/historical-redux2#148]
When using the MP6 plugin (the admin design altering plugin) it creates hover issues in the tabs. The text will jump below the icon and back repeatedly. 
![screen shot 2013-08-22 at 2 48 14 pm](https://f.cloud.github.com/assets/4382867/1011818/e5ba7a32-0b63-11e3-980d-0e24e6b6c5e2.png)

**Comment by dovy** [comment]
I have already fixed this in 3.0. Worry not, it's already done.  ;)

**Comment by dovy** [comment]
I also just fixed the menu icon if MP6 is set to use the default gear of wordpress. We'll need to see how with MP6 we can pass in the icon class rather than an actual icon for future releases. That's up to the Wordpress team.  ;)
