### ISSUE TITLE
Upload Field : Value should be stored in the database as the attachment ID

### ISSUE THREAD

**Issue by mcaskill** [evertiro/historical-redux2#149]
File : /options/fields/upload/field_upload.js

Currently, the Upload Field stores the _attachment URL_ in the database. I think it would be more practical to store the _attachment ID_ and offer a field setting to return value as either _Object_, _URL_, or _ID_.

``` php
array(
    'id' => 'foobar',
    'type' => 'upload',
    'title' => __('Lorem Ipsum'),
    'std' => get_template_directory_uri() . '/images/qux.png', // or an attachment ID
    'format' => 'id' // url, object, id
)
```

This will permit a wider range of control over the attachment, such as choice of image size and post meta.

I'd offer a pull request but I'm still unfamiliar with the [Settings API](http://codex.wordpress.org/Settings_API) at the moment and thus haven't looked into it yet.

Cheers,

**Comment by evertiro** [comment]
We've got a complete rewrite of the media manager in v3.0.0, you get your wish!
