### ISSUE TITLE
Fold - Linking Field Visibility by Value - READ

### ISSUE THREAD

**Issue by dovy** [evertiro/historical-redux2#154]
Hey all. So I just implemented what I consider to be a killer feature in Redux for 3.0. Now some other frameworks have considered things like this before. This is the concept of `folding` or hiding values based on the value of a parent. I know Redux has had a `hide_below` field before. SMOF also allowed for fold, so the concept came largely from there. However, I've taken it to a whole new level. Complete with nesting to any level.

I invite you to read this page, and give me your input. I want to make sure this new documentation we're making is clear and concise. 3.0 is really shaping up and I hope you can feel the energy. Look forward to next week!

http://reduxframework.com/docs/fields/defining-fields/field-arguments/fold/

**Comment by lumberman** [comment]
Multiple values is amazing folding options for me!
Thank you very much for your time implementing this feature. I'm looking forward to switch my themes to the new version of Redux.

**Comment by dovy** [comment]
@pavot I'm so glad you're happy about this. There will be a little pain in conversion to the new option types, but the pain will be greatly worth the benefit.

**Comment by dreamzsiva** [comment]
The example at the location https://gist.github.com/dovy/6478863 shows how to use fold with a Switch type parent. 
However, I want to use fold with a Array type parent. For eg. in the below code, I want Cat_select to be displayed when user selects images with id 1 or 2 from Layout_1 (which is the parent).

Can you please tell me how I can accomplish that ?

array(
                'id'=>'layout_1',
                'type' => 'image_select',
                'compiler'=>true,
                'title' => __('Main Layout', 'redux-framework'), 
                'subtitle' => __('Select main content and sidebar alignment. Choose between 1, 2 or 3 column layout.', 'redux-framework'),
                'options' => array(
                        '1' => array('alt' => '1 Column', 'img' => REDUX_URL.'assets/img/1col.png'),
                        '2' => array('alt' => '2 Column Left', 'img' => REDUX_URL.'assets/img/2cl.png'),
                        '3' => array('alt' => '2 Column Right', 'img' => REDUX_URL.'assets/img/2cr.png'),
                        '4' => array('alt' => '3 Column Middle', 'img' => REDUX_URL.'assets/img/3cm.png'),
                        '5' => array('alt' => '3 Column Left', 'img' => REDUX_URL.'assets/img/3cl.png'),
                        '6' => array('alt' => '3 Column Right', 'img' => REDUX_URL.'assets/img/3cr.png')
                    ),
                'default' => '2'
                ),

```
        array(
            'id'=>'cat_select',
            'fold' => array('layout_1' => array( 1, 5 )),
            'type' => 'select',
            'data' => 'categories',
            'multi' => true,
            'title' => __('Categories Multi Select Option', 'redux-framework'), 
            'subtitle' => __('No validation can be done on this field type', 'redux-framework'),
            'desc' => __('This is the description field, again good for additional info.', 'redux-framework'),
            ),
```

**Comment by davidmcnee** [comment]
Thanks for a great job on the new Redux!

I'd like to use the fold with the parent as an image select. Is it possible?

Cheers

**Comment by dovy** [comment]
@circularone It should be working now. Give it a try.

**Comment by davidmcnee** [comment]
Thanks Dovy, works great!
Now i'm trying to use the fold with the parent on another option page? Just trying to do it with a switch but not having any luck?

Cheers

**Comment by dovy** [comment]
@circularone Please do a new issue and provide more steps so that I can reproduce. Thanks.
