### ISSUE TITLE
Feature request: padding/margin field

### ISSUE THREAD

**Issue by teamcrisis** [evertiro/historical-redux2#155]
Instead of using four separate fields for top/right/bottom/left, can we get a field where it's handled all in one?

**Comment by dovy** [comment]
@teamcrisis Which field are you referring to? I think that's a good idea. We'd still set it as all 4, but within a single argument.

Again, however, which field are you referring to?

**Comment by dovy** [comment]
Also you can always add a class to you fields...

**Comment by teamcrisis** [comment]
@dovy I envisioned it as 4 numbers-only fields, inline with each other, with labels above or below each input to make it clear to the user. If you really wanted to go all out, maybe add an ability for the developer to set whether the values should be in pixels or percentage, then display that metric to the right of each field. The data returned would then include the number and metric.

**Comment by dovy** [comment]
@teamcrisis Done and committed to the new repo.

http://preview.simplerain.com/q8Kk

It will be up on the demo later today.

Sorry for the delay on the new version. We're working through some code rewriting issues.

**Comment by teamcrisis** [comment]
@dovy thank you. Looking forward to testing it out!

**Comment by dovy** [comment]
@teamcrisis Planned release is tonight. Try out your spacing field here:
http://demo.reduxframework.com/wp-admin/admin.php?page=redux_options&tab=3

**Comment by teamcrisis** [comment]
@dovy excellent. Looking forward to testing v3 later tonight or tomorrow morning. Thanks again, great job with it!
