### ISSUE TITLE
css validation issue.

### ISSUE THREAD

**Issue by afzaalpersonal** [evertiro/historical-redux2#158]
The css validation in v3.0 used the came class to extend ReduxFramework, this being:

Redux_Validation_html

Changing this to:

Redux_Validation_css prevents the issue occuring.

**Comment by dovy** [comment]
Please use the https://github.com/ReduxFramework/ReduxFramework/ issue tracker for issues regarding 3.0.

I've also resolved the issue here:
https://github.com/ReduxFramework/ReduxFramework/commit/e4d77249369092e2c8069106c13e63491b4880b5

Thank you!
