### ISSUE TITLE
Checkbox css switcher

### ISSUE THREAD

**Issue by denis0706** [evertiro/historical-redux2#18]
I have just implemented css switcher style for checkbox field.
http://jsfiddle.net/LeBen/9aJDc/
Also fallback is applied ( browser <= 8ie shows standart checkbox)
You can control it by adding key 'switch'  (true/false) to field array.

**Comment by denis0706** [comment]
If you think it must be in framework i will pull a request.
I have already updated my fork
https://github.com/denis0706/Redux-Framework

**Comment by evertiro** [comment]
Love it! Just pushed a bunch of changes... Might as well keep improving while we're on a roll! Go ahead and send a pull request!

**Comment by evertiro** [comment]
c32c4702a5f9947a2c0264d21bb69d9c541e03b5
