### ISSUE TITLE
File Upload Context

### ISSUE THREAD

**Issue by onurozkan** [evertiro/historical-redux2#19]
in wordpress 3.5, if you have multiple file upload fields, when you change file, its changing all previews fields. some fields are needs context.

**Comment by onurozkan** [comment]
i dunno github much, but here is my fix.

https://github.com/onurozkan/Redux-Framework/commit/5cce1a95f97b09e4f9e4b525109bd1d3de5eda9b

**Comment by onurozkan** [comment]
fixing remove too. 

https://github.com/onurozkan/Redux-Framework/commit/f23ee34f67f5d33a5583775463c5fb238dc0f034

**Comment by evertiro** [comment]
Seems you figured out GitHub after all! Welcome to our little community, and thanks for the fix!
