### ISSUE TITLE
Upload button not triggering

### ISSUE THREAD

**Issue by BenRacicot** [evertiro/historical-redux2#21]
Hello,
I noticed that the upload button within the Custom Fields tab and or when reusing the upload type array doesn't popup the WordPress upload box. Am I missing something?

**Comment by denis0706** [comment]
Hi,
We have discussed that problem here https://github.com/ghost1227/Redux-Framework/issues/11
Only one problem i have found was adblock borwser plugin blocked popup.
What version of wp do you use?

**Comment by BenRacicot** [comment]
Thanks for replying Denis. Yes it doesn't look like that one is fixed just yet. 
No popup blockers at all and checked on FF + Chrome.
I'm on the new 3.5. with both a local Wamp setup and a live test site too. 
How can I help?

**Comment by evertiro** [comment]
Sorry I didn't catch this sooner, are you still having issues with the upload button?

**Comment by BenRacicot** [comment]
Well I tried the new versions with the options.php changed to default.php and haven't been able to get the options to show in admin... But yes I'm afraid on twenty Eleven and a theme called Accord both on fresh installs, several browsers and a live/WAMP setup... UGH.

I will keep at it tho. Thanks for looking out.

**Comment by evertiro** [comment]
Please try the latest development build and let me know if this is still an issue for you.

**Comment by BenRacicot** [comment]
Hey man,

Thanks for the update.
I've spent a lot of time trying to figure this out and I hope you will have
patience with me here:

I haven't been able to get Redux installed correctly since my initial
attempt.
I don't get the readme instructions at all, well they don't work for me
anyways.

Why change the options folder to "admin" (readme)?

get_template_part('theme', 'settings'); how does that include default.php?
Am I missing something obvious here? I'm sure I must be.

It's okay to remove defaults.php from it's home in the, now named, 'admin'
folder?

And I give up on learning GIT. SCrew it, someone will have to go over it
with me in person someday, but I've spent days banging my head against it
now.

Anyways thanks for getting at me and sorry for my newbness.

This is my current install:
[image: Inline image 1]
Please tell me where I can help after I get Redux going again.
-Ben

**Comment by evertiro** [comment]
Do you have Skype? I'd be more than happy to give you a primer on Git as well as setting up the basics of Redux.

**Comment by BenRacicot** [comment]
Oh yeah! Thank man.

it's BenRacicot or look me up via benjaminracicot
