### ISSUE TITLE
ask about licence

### ISSUE THREAD

**Issue by joanhard** [evertiro/historical-redux2#25]
Hi, that's great framework one
What license type of redux framework? I can't found in readme file
can I selling my themes use that framework?

Thank you

**Comment by evertiro** [comment]
You are more than welcome to use Redux in any project, free or commercial. Redux is released under the same licensing as WordPress itself, GPL. Guess I should mention that somewhere huh...

**Comment by joanhard** [comment]
Hi nice info for me,
I think all about wordpress would be release under GPL, lol

Thank you
