### ISSUE TITLE
button set scroll the page up

### ISSUE THREAD

**Issue by riyaku** [evertiro/historical-redux2#27]
When we click the button of buttonset field type, it scroll the page up. How can we prevent this?

**Comment by evertiro** [comment]
That's odd... I use buttonset regularly and haven't seen this happen. Can you provide specifics about the environment used? WP version, browser and the like?

**Comment by riyaku** [comment]
Wp 3.5, Firefox 17.0.1, Windows. I recorded the behaviour here http://screencast.com/t/62SLQJ9C

**Comment by evertiro** [comment]
I still can't reproduce this, when I get home I'll try it on Firefox/Windows and see if it's that combination. Any of my other users able to reproduce this bug?

**Comment by evertiro** [comment]
Is this still occurring with the most recent dev release?

**Comment by riyaku** [comment]
It works perfectly now. Thanks

**Comment by evertiro** [comment]
No problem! Glad the issue got resolved.
