### ISSUE TITLE
Release a next stable version of Redux Framework

### ISSUE THREAD

**Issue by kwayyinfotech** [evertiro/historical-redux2#28]
Hello,

I tried the Master branch and it's working perfectly. I think there should be a pending list for next release.

Currently, Redux Framework is at v1.0.0 as on https://github.com/ghost1227/Redux-Framework page.

Most of the new features are now working (in Master branch) and there should be a pending list so we can plan next release something like v1.2.0 or v2.0.0 (or any version number that you want to). This will also help us to create wiki/documentation as we have fixed features for feature list.

**Comment by evertiro** [comment]
I just updated the commit list on the README... Good timing! I've got tomorrow off work and plan to put some effort into docs, and prepping for the 1.1.0 release (yay New Years release!).

**Comment by evertiro** [comment]
Redux v2.0 was just released!
