### ISSUE TITLE
Need a free (without attribution) iconset

### ISSUE THREAD

**Issue by evertiro** [evertiro/historical-redux2#3]
As my predecessor noted, an iconset with a more commercial-friendly license is needed. If anyone has any suggestions, please feel free to let me know. Additionally, if anyone knows a designer who would be willing to work something out, that is fine with me as well.

Along the same lines, what are people's thoughts regarding releasing a branch of Redux that is built specifically to work with iconfonts instead of images?

**Comment by evertiro** [comment]
Options that were brought up in the previous thread:

<b>Icon Sets</b>

<ul>
<li><a href="http://glyphicons.com/">glyphicons</a> - Current set, requires attribution</li>
<li><a href="http://pixel-mixer.com/">Pixel Mixer</a> - Site is offline</li>
<li><a href="http://www.iconsweets2.com/">iconSweets2</a> - Good option, if someone converts it to PNG</li>
<li><a href="http://brankic1979.com/icons/">Pixel Perfect</a> - Good license, lacks important icons (ie, social icons)</li>
<li><a href="http://icomoon.io/">IcoMoon</a> - Ultimate pack is the best option I've seen yet, but it's not free (anyone want to <a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=QQJDSRRZVKRGU">donate</a>?)</li>
</ul>

<b>Icon Fonts</b>

<ul>
<li><a href="http://fortawesome.github.com/Font-Awesome/">Font Awesome</a> - Requires attribution</li>
</ul>

**Comment by vitaliykononov** [comment]
Maybe some of this will works?
http://speckyboy.com/2010/08/09/30-fresh-and-free-icon-sets-for-designers-and-developers/

**Comment by evertiro** [comment]
All of the sets in that list that contain the necessary icons require attribution or aren't free :( Good try though! :)

**Comment by bimaljr** [comment]
Why don't we use Font Awesome:
http://fortawesome.github.com/Font-Awesome/

All icons are scalable vector graphics means icons look awesome at any size.

**Comment by briancwelch** [comment]
Font-Awesome would be an amazing implementation.

**Comment by evertiro** [comment]
Once the major changes to the framework are done, I will be releasing a branch (that I'm currently using myself) which replaces the icons with iconfonts. However, not everyone wants this (custom icons/etc) so I still need a standard iconset which doesn't require attribution.

**Comment by cyberwani** [comment]
I think Font-Awesome can be a better option. As, if someone wants his own custom icons then he can use his own css properties to replace Font-Awesome icons.

**Comment by evertiro** [comment]
The problem with doing a solely iconfont release is that the css has to be changed fairly significantly to allow it. Hence my plan to have two branches, one graphic based and one iconfont based. Even then, we still have to problem of attribution... Font-Awesome, while it is an... awesome solution, requires attribution. I'd prefer an option that _doesn't_ require any attribution.

**Comment by briancwelch** [comment]
I'll have to do some more searching to see if I can come up with anything similar that doesn't require attribution.  

 I was playing around last night and implemented Font-Awesome and it seemed pretty easy to get in and working.  My only issue, of course, was the 'icon' argument for the tab arrays.  I'm still fairly new to the framework, so I wasn't sure where to change the icon argument so I could just use css class.  Instead, I had to put it in next to the description argument; it worked just fine, but then I was "missing an image" in the tab.   

I have been personally using the Silk Icon set by Famfamfam.  Though, as is my understanding, it requires attribution as well.

**Comment by evertiro** [comment]
And that's exactly why I'm releasing two separate branches :)

**Comment by bimaljr** [comment]
Here is another font based icon set:
http://www.zurb.com/playground/foundation-icons

I don't find licence/usage on their site so I am not sure for the usage.

**Comment by bimaljr** [comment]
Here is the Foundation Icon font licence:
https://github.com/zurb/foundation-icons/blob/master/README.markdown

Original Icon Pack link:
http://www.zurb.com/playground/foundation-icons

**Comment by bimaljr** [comment]
Also here are list of font based icons:
http://fontello.com/

There are different licenses for each package. I am not sure for which license is suitable for Redux.

**Comment by alexpos** [comment]
http://gemicon.net/

**Comment by evertiro** [comment]
Now there's a possibility!

**Comment by kwayyinfotech** [comment]
There is a good news :)
Font Awsome has released new vesion 3.0 with more open licence:
http://fortawesome.github.com/Font-Awesome/

"SIL open font license, MIT license for code. No more attribution required, but much appreciated."

**Comment by evertiro** [comment]
That's the best news I've heard in ages! Thanks! Thanks to this little licensing update, Redux v2.0 will ship with full iconfont support!

**Comment by evertiro** [comment]
Redux v2.0 was just released and features full Font Awesome support with a flag to revert to image-based icons (icons no longer included... so no attribution needed and a much leaner package).

**Comment by kwayyinfotech** [comment]
Great.. will test it

**Comment by denis0706** [comment]
Font Awesome  is really good and easy to use. One improvement we can make is set a flag not to args, but to sections, so one section can use image-icon while another one - font icon.

**Comment by evertiro** [comment]
Not a bad thought

**Comment by peter-nl** [comment]
Over at the wp theme team they just published on Genericons, that are now baked into Twenty Thirteen: http://themeshaper.com/2013/02/27/genericons-icon-font/  
Probably Redux could use that same font?

**Comment by evertiro** [comment]
We've been officially using Font Awesome ever since they changed their licensing... No complaints yet!
