### ISSUE TITLE
Is it okay to make premium themes using Redux ?

### ISSUE THREAD

**Issue by vitalieb** [evertiro/historical-redux2#31]
Is it okay to make premium themes using Redux ?
Does GPL 2 allow that ?

http://reduxframework.com/ says : Code licensed under the Apache License v2.0. Documentation licensed under CC BY 3.0.

But the license that comes with Redux is GPL 2

**Comment by evertiro** [comment]
Sorry, copy paste fail. Redux is licensed under GPL. Commercial use is allowed.
