### ISSUE TITLE
How about a multi image upload - for Sliders

### ISSUE THREAD

**Issue by vitalieb** [evertiro/historical-redux2#32]
I thought it would be a good idea to add a multi image upload function so it would be possible to use that in Sliders.

For example I add an image using the old uploader (3.4) than press some jQuery   +  and I can add one more image .. all the image paths are stored in an array.
But if I use the 3.5 uploader I just select more than one image.

Also using the jQuery UI .sortable() it would be possible to arrange the order of the images in the slider by dragging them.

So when you want to use more slider types you just combine 2 field types:
- a dropdown select with the Slider type name
- a multi image filed to choose from the images.

or maybe just a "slider" filedset type to be able to generate a preview too :)

**Comment by hamed-alshukri** [comment]
+1

**Comment by BenRacicot** [comment]
Yes I've been trying to find someone to help me extract this funstion from the SMOF theme options. I like REDUX better but that 'draggable/sortable image upload' functionality is needed by almost everybody in a bunch of different circumstances.

What we need is that functionality in a meta box...
If anyone has any recommendations or findings plz post back here.

**Comment by Pushplaybang** [comment]
+1 could be pretty cool

**Comment by KingYes** [comment]
@ghost1227, Are you coding this feature?

**Comment by BenRacicot** [comment]
I'm working on putting this arrangable slider type functionality into a meta box just to start but it's a bit beyond me. If anyone wants to take a look at what I have going on it will eventually be worth it! :)

![arrangable-slider](https://f.cloud.github.com/assets/1815385/207752/c3fd765c-81fb-11e2-9492-d471283d79cb.jpg)

**Comment by djevrek** [comment]
How is this going, this is must have field for every wp theme :)
