### ISSUE TITLE
When opening the options "Settings have changed, you should save them!" appears

### ISSUE THREAD

**Issue by vitalieb** [evertiro/historical-redux2#34]
![Untitled-1](https://f.cloud.github.com/assets/2988222/38398/65e5b3ac-54e9-11e2-90ee-753420e26e5d.png)
When opening the options "Settings have changed, you should save them!" appears although I don't change anything. 
Tried in IE and Chrome .. 
It also happens after saving the changes

**Comment by vitalieb** [comment]
Did this in options.js... 

```
jQuery('input:not(input[class*=font]), textarea, select').change(function () {
    if(this.id === 'google_webfonts' && this.value === '') return;
    jQuery('#redux-opts-save-warn').slideDown('slow');
});
```

of course it's not good but at least it works for the rest .... 
.. will try to find a better solution

**Comment by vitalieb** [comment]
added one line to jquery.fontselect.js:

```
  Fontselect.prototype.selectFont = function(){

    var font = $('li.active', this.$results).data('value');
    this.$original.val(font).change();
    this.updateSelected();
    this.toggleDrop();
    jQuery('#redux-opts-save-warn').slideDown('slow');
  };
```

now everything works just fine

**Comment by evertiro** [comment]
I have yet to experience this, and given I'm still hoping to replace the current preview function with something a bit more robust, I'm noting going to merge this change for the moment. If anyone else experiences this issue, the above solution is a (slightly hackish) way of fixing it.

**Comment by briancwelch** [comment]
Not sure if it's because I'm using two google webfont selections in my back end, but I still get this error, even after applying everyones fixes.  It never goes away.

**Comment by vitalieb** [comment]
Yes it's because of google webfonts ... those selections generate previews and those previews are considered changes ...

**Comment by evertiro** [comment]
Redux v2.0 was just released and I still can't duplicate this error... It is still happening?

**Comment by briancwelch** [comment]
No, I haven't had any issues with it recently at all.  Thank you very much!
