### ISSUE TITLE
new functions to get/show options value

### ISSUE THREAD

**Issue by cyberwani** [evertiro/historical-redux2#36]
Hi @ghost1227,
I added two new functions **redux_get** and **redux_show** to display options data anywhere by passing **field id** and **default value**.
[Click Here](https://github.com/cyberwani/Redux-Framework/commit/fecc689b6fdcb96e491b7e72231e5eb8c0df7af0) to check the code.

**Code is listed below:**

``` php
// get Redux Options data with key name
// Available Parameters
// opt_name: id of the field
// default: default value to display if data returns blank
function redux_get($opt_name, $default = null){
    global $Redux_Options;
    $redux_args_opt_name = $Redux_Options->args[opt_name];
    $redux_data = get_option($redux_args_opt_name);

    return ( !empty( $redux_data[$opt_name] ) ) ? $redux_data[$opt_name] : $default;
}

// show Redux Options data with key name
// Available Parameters
// opt_name: id of the field
// default: default value to display if data returns blank
function redux_show($opt_name, $default = '') {
    $option = redux_get($opt_name);
    if(!is_array($option) && !empty($option) ) {
        echo $option;
    } elseif( !empty($default)) {
        echo $default;
    }
}
```

**Comment by evertiro** [comment]
Posted in the wrong place >_< In what circumstances can you see this being used?

**Comment by Pushplaybang** [comment]
excuse my ignorance, but how is it better than the standard way of doing it ?

**Comment by signo** [comment]
Correct me if i am wrong, but isn't it easier to write $Redux_Options->get('myoption', null) and $Redux_Options->show('myoption', '');

**Comment by Pushplaybang** [comment]
not as easy as in this example i don't think....

``` php
$option = get_option[opt_name];
echo $options[opt_id];
```

unless I'm completely missing the point, but my assumption is we're all talking about rendering the options out ?  if so, it doesn't get much simpler than that.

**Comment by denis0706** [comment]
Agree with Pushplaybang, I like and use this way to get options. While using it we don't rely on redux functions and use native WP  way of getting option values. But in last build we can't use this method, i wrote about it #63 - if we have our array option in DB, new fields won't be set to DB

**Comment by evertiro** [comment]
I'm currently leaning towards closing this. Anyone have a final argument to convince me?
