### ISSUE TITLE
Creating a new field type: removing the left column?

### ISSUE THREAD

**Issue by psaikali** [evertiro/historical-redux2#37]
Hi there,

First of all, thank you so much for your work on this framework, it's incredibly useful.
I'd like to create a new field but I'm stuck with my new class: is there a way to remove the first column that is rendered in the field table? By first column, I mean this > http://img.saika.li/LyK0.
I noticed that this first column code is not part of the render() function.

I'd like to extend/enhance the "info" field so it doesn't close the previous table and opens a new one, resulting in huge top and bottom margins (http://img.saika.li/LyId).

I'll try to give you a hand and code a slider (for number) field. I'd also need to add drag&drop functionality to the multi_text field, I'll do my best to make it work and share it if I succeed ;)

Thx!

**Comment by evertiro** [comment]
Seems you've worked out your issues with the first part of this ticket. Can you elaborate on the second piece? Otherwise I'm going to close this as resolved.
