### ISSUE TITLE
Google Web Fonts API - SSL Certificate Error

### ISSUE THREAD

**Issue by therafiman** [evertiro/historical-redux2#38]
On my test server the wp_remote_get call in field_google_webfonts.php does not retrieve the JSON list but instead returns http_request_failed because it cannot validate the SSL certificate. This can be fixed by using the $args parameter to set sslverify to false:

$fonts = wp_remote_get( 'https://www.googleapis.com/webfonts/v1/webfonts?key=' . $this->args['google_api_key'], array( 'sslverify' => false ) );

**Comment by evertiro** [comment]
What version of Redux are you running? This issue was solved quite a while ago, and that method used to retrieve the webfonts was deprecated a few weeks back.

**Comment by therafiman** [comment]
Sorry my mistake, I was using the stable branch instead of master.
