### ISSUE TITLE
Need a documenter

### ISSUE THREAD

**Issue by evertiro** [evertiro/historical-redux2#4]
If anyone is good at writing documentation, please let me know. I am probably the worst person to talk to in regards to writing docs, although I'm pretty good about commenting my code, and we are sorely lacking in terms of our wiki.

**Comment by kwayyinfotech** [comment]
There are two places for documents. First, Github Wiki page and second is on http://reduxframework.com/ where we will create a page and add content in it.

I think to expand the Github Wiki page so anyone can edit it.
Also there should be different sections like this:
- **Getting Started:** Here we will add first step to install it in any theme. Also we can show them different options like create a child theme etc.
- **File Structure:** Here we can show file structure so user can get which file to edit.
- **Different fields with their options:** Here we will show each field options. We need to add all possible options of each fields. Also if we added any new option in any field (in our new version of Redux) than we also need to add Redux version number of the feature. So user will first check their Redux version before using the new option displayed in this section.

I am not native English speaking person (I am bad in spelling grammar mistakes) so I cannot write document text. But we can decide different blocks like above.

**Comment by bonnieshull** [comment]
I'm am both very good at writing documentation and very much a n00b with theme options and having a hard time with this. If someone can take an hour or so on IM with me to walk me through getting setup I will be happy to thoroughly document the process and maintain the documentation over time.
