### ISSUE TITLE
Various small but useful enhancements

### ISSUE THREAD

**Issue by psaikali** [evertiro/historical-redux2#40]
![screen-2013-01-07-2 45 07 PM](https://f.cloud.github.com/assets/1606655/47810/a1006906-58e9-11e2-9b4c-657654683540.png)
I'm quite n00b to github and haven't cloned/forked the repo, so no way to pull-request my changes. I'll share this the ol' way ;)

Just added a select dropdown to the color gradient, including "vertical" / "horizontal" options. Might be useful for someone someday.

field_color_gradient_dir.php > http://img.saika.li/LzQo
## 

![screen-2013-01-07-7 17 56 PM](https://f.cloud.github.com/assets/1606655/48484/c1ad0d50-590f-11e2-8dbe-5e80d27325f8.png)
Modified the post_type_select so it can accept a 'multiple'=>true parameter to be able to choose multiple content types.

field_post_type_select.php > http://img.saika.li/LziQ

Enjoy!

**Comment by evertiro** [comment]
Is this part of your recent commit?

**Comment by psaikali** [comment]
Yup, ignore this one

post_type_select isn't yet, but I'll add it as a separate pull request soon.

**Comment by evertiro** [comment]
Closing until a pull request is posted
