### ISSUE TITLE
std value not set

### ISSUE THREAD

**Issue by pcescato** [evertiro/historical-redux2#41]
'std' values are not set by default when I activate a theme, neither after a first update.
For example, 'std' => array('from' => '#000000', 'to' => '#FFFFFF') in samples, causes an error as there's a validation on those fields...
Or 'id' => '10', 'std' => '1' is set as OFF...
Platform: WordPress on WAMP Server (PHP 5.4, WP 3.5)

**Comment by evertiro** [comment]
Resolved with commit 1f0d5f6783566906659c0ec5f87364f45f6d6523
