### ISSUE TITLE
Getting a field type

### ISSUE THREAD

**Issue by psaikali** [evertiro/historical-redux2#45]
I added this function to the class to retrieve a field type, but I'm wondering if there is a better way to do it, as looping through each section might not be the most efficient way to do it:

```
      function type($opt_name) {
        foreach($this->sections as $k => $section) {
            if(isset($section['fields'])) {
                foreach($section['fields'] as $fieldk => $field) {
                    if ($field['id'] == $opt_name) return $field['type'];
                }
            }
        }
    }
```

Feedback welcome!

**Comment by evertiro** [comment]
I'm sure there's a better way, but I'm about burned out at the moment. Given this hasn't had any love yet, does the community have any thoughts? Otherwise I'll ponder it some more and get back to you.

**Comment by evertiro** [comment]
One question... Why?

**Comment by psaikali** [comment]
Cool, thx! It's working fine for now, but I'm wondering if there is a
better and more efficient way.

I'm using this function because I created a generate_css_styles() function
that outputs some css code based on the id of some of my options. So I need
to know the  setting (field) type to generate the appropriate code.

BTW I'll re-pullrequest my new fields someday next week, been pretty busy
but I'll share my (stable) enhancements asap, promise!

**Comment by evertiro** [comment]
Awesome! Looking forward to it!

**Comment by evertiro** [comment]
Still waiting on pull requests, but I'm closing this issue as I still don't have a better way to handle it.
