### ISSUE TITLE
Using the Redux Framework, not able to open "Upload" window

### ISSUE THREAD

**Issue by ghost** [evertiro/historical-redux2#50]
First off, thanks so much for putting this together. I am hoping to get this all up and running asap so our application can get live soon. 

As of right now, I have the upload option setup, but when I click the button it doesn't trigger anything. The href associated with the button is "javascript:void(0);". If there is any other information that would be helpful to debugging, please let me know and I can get that for you.

Thanks so much for the help!

**Comment by evertiro** [comment]
Can you tell me what version of Redux you're using (or when you downloaded it), as well as your current WordPress version and web browser?

**Comment by ghost** [comment]
I downloaded the Redux stable release, and current WP version is 3.5, and browser is Chrome.

**Comment by evertiro** [comment]
Try using the dev release, I believe the Media Uploader patch was after the last stable release.

**Comment by ghost** [comment]
You're exactly right. That resolved the issue. It looks great, thanks for all your help!
