### ISSUE TITLE
Hiding Dev mode doesn't work in latest build version

### ISSUE THREAD

**Issue by ghost** [evertiro/historical-redux2#51]
I'm not able to hide the dev mode tab when using the latest build version. This was working in the previous version.

**Comment by evertiro** [comment]
It's working fine for me... Can you verify that you are setting $args['dev_mode'] = false; in options.php?

**Comment by ghost** [comment]
Yes, that is confirmed. 

```
    function change_framework_args($args){
    $args['dev_mode'] = false;
    return $args;
    }
    add_filter('redux-opts-args-twenty_eleven', 'change_framework_args'); 
```

**Comment by evertiro** [comment]
Nope, you're in the wrong place. Go down a few more lines.

**Comment by ghost** [comment]
Ah perfect, it moved on me. Working like a charm now. :) Thanks so much!!
