### ISSUE TITLE
Make fields not to extend  Redux_Options class.

### ISSUE THREAD

**Issue by denis0706** [evertiro/historical-redux2#54]
Why do we need to extend  field class with Redux_Options class?
Fields don't use Redux_Options  functions, only vars.
But we have already passed vars to field class in Redux_Options at `function _field_input($field)`:
`$render = new $field_class($field, $value, $this);`
I suppose we can remove class extend to prevent doing unnecessary work, such as unused variables initialization and database requests.

**Comment by evertiro** [comment]
The __construct function (as it is currently written) requires access to the parent. Without extending Redux_Options, there is no parent. If you have ideas as to a better way to handle this, I'm all for it. For now, I'm closing this issue though.

**Comment by denis0706** [comment]
https://github.com/denis0706/Redux-Framework/commit/231f9693d03523f8b60decae3bb847bb3cb612c7

**Comment by evertiro** [comment]
Testing says all systems are go! Thanks for the suggestion!
3e846327faad1b81e022d2b183adc93dcbf3bf0e
