### ISSUE TITLE
Redux Options for Customizer.

### ISSUE THREAD

**Issue by Pushplaybang** [evertiro/historical-redux2#56]
I think it would be an incredible feature, (and maybe quite a fair challenge) to look at some integration between the Redux Framework and the rather snazzy new WordPress customizer.

**Comment by psaikali** [comment]
+1

**Comment by hiro288** [comment]
+1
*
Naeem N. Belushi\* - Web Developer | Portfolio http://naeemnur.com |
Bloghttp://cssreflex.com

 http://cssreflex.com

**Comment by psaikali** [comment]
Actually I thought about that, and I'd like to add my own 2 cents: being able to "duplicate" some specific fields from the settings page, to display them in the new WP customizer, would be awesome. I thought about implementing some specific color/text settings in the new WP customizer, while having other general settings in my theme settings page, but that might be confusing for the user to have multiple places to edit the theme settings.

So having some settings on BOTH pages (current settings page + WP customizer) would be awesome. Not sure if doable, but awesome ;)

**Comment by hamed-alshukri** [comment]
+1

**Comment by hamed-alshukri** [comment]
+1

**Comment by evertiro** [comment]
Perfectly doable, but I have no experience with the customizer. Does anyone have experience? Or a good reference?

**Comment by Pushplaybang** [comment]
I don't have any experience but I've seen a couple great tutorials and I was reading somewhere about another framework where they looped through the settings to duplicate them....  I'll have a look for some links to tuts etc (I know there were some good looking ones by Otto and on WP tuts).

Theoretically it would be cool to pass an option when creating the tabs, and fields, whether to include them in the customizer or not.

**Comment by Pushplaybang** [comment]
Codex : 
https://codex.wordpress.org/Theme_Customization_API 

Links from Otto
http://ottopress.com/2012/how-to-leverage-the-theme-customizer-in-your-own-themes/
http://ottopress.com/2012/theme-customizer-part-deux-getting-rid-of-options-pages/
http://ottopress.com/2012/making-a-custom-control-for-the-theme-customizer/

WP tuts
http://wp.tutsplus.com/tutorials/theme-development/digging-into-the-theme-customizer-overview/
NB : this is the first in a series of four articles they have going through the practicality of using the theme customizer

Other : This guy has another options framework where he's working through this as well.
http://wptheming.com/2012/07/options-framework-theme-customizer/
this one also looks great :
http://themefoundation.com/wordpress-theme-customizer/

I'd love to be more help, but I'm still coming to terms with the widget API and have barely scratched the surface of the settings API, which i think is probably required reading for digging into the customizer.

Hope this helps.

**Comment by evertiro** [comment]
That's awesome! Thanks! I'll look into this tonight/tomorrow (this weekend at the latest).

**Comment by Pushplaybang** [comment]
Sweet.  Thinks it would be a pretty major feature.

**Comment by ghost** [comment]
This would be awesome!

**Comment by ghost** [comment]
Any update on this?

**Comment by evertiro** [comment]
Been researching it, but it hasn't been at the top of the priority list, and unfortunately I still have to maintain a regular job :frowning: It's in development though!

**Comment by ghost** [comment]
In development is good (and we all have jobs to tend to).  Keep up the good work and I look forward to seeing it when it is implemented.

**Comment by corradomatt** [comment]
Hey @ghost1227, any updates on this one? I'm very interested in seeing this worked out. I understand you're probably very busy....I am too but I'd like to help if possible. Is there a branch somewhere that I can contribute toward this feature?

**Comment by dovy** [comment]
Working on it. May not be a part of 3.0, but eventually.  ;)

**Comment by dovy** [comment]
Closed. Feature request moved to new repo.
