### ISSUE TITLE
Hide more than 1 field

### ISSUE THREAD

**Issue by hectorgarrofe** [evertiro/historical-redux2#57]
Hello,

Is there a way to hide more than the field below a checkbox?

Using "checkbox_hide_below" works great. But sometimes I need something like "checkbox_hide_3below", or "checkbox_hide_4below".

I do not know if I have explained correctly. Basically, would be nice to hide multiple fields, no only the one below.

Thanks for your great job!

**Comment by hamed-alshukri** [comment]
In the latest version (development branch), you can do it using 'checkbox_hide_below' field type. Just add an argument 'next_to_hide' with the number of fields you want to hide. 
I hope this is what you're asking for.

**Comment by hectorgarrofe** [comment]
Sorry,

I found this looking other issues:

'type' => 'checkbox_hide_below',
'next_to_hide' => 2

To hide the desired number of fields.

And:

'type' => 'checkbox_hide_all,

To hide all the fields below this field.

I's great to has this implemented! :)

But I can't found it on the Documentation... If you are interested I can help you writting it.

Thanks again!

**Comment by hectorgarrofe** [comment]
Thanks for your answer @UniqueCreativity!

**Comment by evertiro** [comment]
The docs are certainly a bit out of date, and probably always will be. Even in a perfect scenario, they will probably only be updated for the stable branch. Glad you got your answer though!
