### ISSUE TITLE
Last Tab Fix

### ISSUE THREAD

**Issue by hamed-alshukri** [evertiro/historical-redux2#65]
In the latest update in the master branch, last tab had been fixed after saving the options. Unfortunately there is a problem when you click on one of the sub menus which should direct you to the appropriate tab. What really happen is the link direct the user to the last tab. The solution is to wrap the elseif statemant in brackets.

In the default.php file, the code on line 591 

```
        $this->options['last_tab'] = (isset($_GET['tab']) && !get_transient('redux-opts-saved')) ? $_GET['tab'] : (isset($this->options['last_tab']) && get_transient('redux-opts-saved')) ? $this->options['last_tab'] : $this->args['last_tab'];
```

should be like this

```
        $this->options['last_tab'] = (isset($_GET['tab']) && !get_transient('redux-opts-saved')) ? $_GET['tab'] : ((isset($this->options['last_tab']) && get_transient('redux-opts-saved')) ? $this->options['last_tab'] : $this->args['last_tab']);
```

**Comment by denis0706** [comment]
Thanks.
My fault, I haven't tried all conditions. Don't know about strange behavior of ternary operator in PHP

**Comment by ghost** [comment]
Thank you for this update. Works great, even though we had to modify defaults.php!

**Comment by evertiro** [comment]
Don't need to modify defaults.php anymore! This has officially been fixed!
