### ISSUE TITLE
google font field error ?

### ISSUE THREAD

**Issue by Pushplaybang** [evertiro/historical-redux2#67]
Hey, this pops up above the google font field with wp_debug set to true (assume it wouldn't be there with debug set to false, but haven't tried.)

Notice: Undefined variable: placeholder in /Applications/MAMP/htdocs/Starter-Theme/wordpress/wp-content/themes/nona-start/functions/options/fields/google_webfonts/field_google_webfonts.php on line 28

**Comment by evertiro** [comment]
Fixed ef1a80383671321165886e54ff9be3bcc127b661

**Comment by Pushplaybang** [comment]
nice one.
