### ISSUE TITLE
Reducing number of files

### ISSUE THREAD

**Issue by ghost** [evertiro/historical-redux2#68]
Hi,

Curious if there's a way to reduce the footprint on this a bit? Seems like 429 files is a bti heavy. Looking for suggestions on making this a little more lightweight. Thanks!

**Comment by evertiro** [comment]
A good chunk of that (almost all of it in fact), comes down the the icons. This will all be going byebye when I release v2.0 which drops static icons in favor of fonticons.

**Comment by evertiro** [comment]
If you want to slim it down now, simply remove any icons you're not using!

**Comment by ghost** [comment]
Okay thanks. Also wasn't sure if consolidating all of the files within the "fields" and "validation" folders would help. But if so, I'd lose the changes made in 2.0, right?

**Comment by evertiro** [comment]
Yes, you'd lose the changes.

**Comment by ghost** [comment]
Okay. Perhaps you're right. Slimming down the 350 icons to just the core few I use may help. However, with an update, those will appear again? 

Also, what's your ETA on 2.0? Am just curious.

**Comment by evertiro** [comment]
Redux v2.0 was just released! :smiley:
