### ISSUE TITLE
Ability to have icon & image option for section icon

### ISSUE THREAD

**Issue by ghost** [evertiro/historical-redux2#72]
While migrating my theme-options.php to the new 2.0 dev channel, I realized a potential feature request? For my "home tab" I like to specify my own icon which is a `.png` file. I noticed with 2.0 it's not working because it's trying to put my `.png` into the `<i>` section. 

Is there a way to do this already that I'm missing or is it a feature request?

Thanks again!

**Comment by evertiro** [comment]
I hadn't added that ability yet, but it's on my todo list

**Comment by evertiro** [comment]
Added! 08cb4c962fc44b8e3a0a8177514079a8d0ab0f31
