### ISSUE TITLE
Redux needs a logo!

### ISSUE THREAD

**Issue by evertiro** [evertiro/historical-redux2#75]
With todays launch of a twitter feed for Redux, I've realized that some fresh graphics are in order. Anyone in the community want to tackle the challenge of designing a logo and icon for Redux? Take a look at other WP frameworks for inspiration and post your suggestions!

**Comment by djevrek** [comment]
I played a bit :)
![redux-logo4](https://f.cloud.github.com/assets/412686/127387/3f947378-6f97-11e2-95b9-bcb3db7ca073.png)
![redux-logo3](https://f.cloud.github.com/assets/412686/127388/3fadfef6-6f97-11e2-9887-83a0afdd0c99.png)
![redux-logo2](https://f.cloud.github.com/assets/412686/127389/3fcbfb40-6f97-11e2-8edd-562e467bf8a0.png)
![redux-logo1](https://f.cloud.github.com/assets/412686/127390/3fe0f842-6f97-11e2-92c1-5798fd0ce432.png)

**Comment by ghost** [comment]
I like the gray R in the circle!

**Comment by evertiro** [comment]
The gray R is definitely the cleanest so far!

**Comment by signo** [comment]
2 versions i put together today.

![redux-1](https://f.cloud.github.com/assets/944774/129654/a4456b02-6fe6-11e2-8e66-f8a699146c12.jpg)
![redux-2](https://f.cloud.github.com/assets/944774/129656/afdb0206-6fe6-11e2-8df3-0998aa25fc39.jpg)

**Comment by evertiro** [comment]
I actually like the second idea there too, not really conducive for an icon though

**Comment by signo** [comment]
Here is one with an icon
![redux-3](https://f.cloud.github.com/assets/944774/129883/a3b43ea0-6ff2-11e2-819d-0a54664c060c.jpg)

**Comment by signo** [comment]
last one, at least for today
![redux-4](https://f.cloud.github.com/assets/944774/129945/16802ad0-6ff7-11e2-8fdc-709737aeac18.jpg)

**Comment by evertiro** [comment]
Love where that one's going!

**Comment by hamed-alshukri** [comment]
![redux-logo-preview](https://f.cloud.github.com/assets/1812192/131077/4fdc5f96-7048-11e2-89ea-8117680fb53d.png)
Here's a simple logo

**Comment by denis0706** [comment]
![redux](https://f.cloud.github.com/assets/3092502/132692/11c0267e-708f-11e2-879a-a996be180945.jpg)

**Comment by evertiro** [comment]
That's not bad either!

**Comment by psaikali** [comment]
Nice work Denis, I love it on a black background!

2013/2/6 Denis notifications@github.com

> [image: redux]https://f.cloud.github.com/assets/3092502/132692/11c0267e-708f-11e2-879a-a996be180945.jpg
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ghost1227/Redux-Framework/issues/75#issuecomment-13198584.

## 

Pierre Saïkali
psaikali@gmail.com

**Comment by evertiro** [comment]
These two are my current favorites...

![](https://f.cloud.github.com/assets/944774/129945/16802ad0-6ff7-11e2-8fdc-709737aeac18.jpg)
![](https://f.cloud.github.com/assets/3092502/132692/11c0267e-708f-11e2-879a-a996be180945.jpg)

Denis, my one issue with yours is that redux is a singular word, so the division of color seems a bit misleading. Maybe try the same idea but with just the checkmark an alternate color?

**Comment by denis0706** [comment]
![redux2](https://f.cloud.github.com/assets/3092502/132811/8caa1cc8-7094-11e2-8466-2cfeda3f0f82.jpg)

**Comment by evertiro** [comment]
Last one on that list is beautiful!

**Comment by evertiro** [comment]
Can you do two inversions of that, one with black text/blue check and one with blue text/black check?

**Comment by denis0706** [comment]
![redux3](https://f.cloud.github.com/assets/3092502/133112/9cc71d0e-709e-11e2-9083-a95e5e5c6a9f.jpg)

**Comment by evertiro** [comment]
The white text/blue check for dark backgrounds, and the second black/blue (the one with the gradient) for light backgrounds win for me. Anyone else have any thoughts?

@denis0706 Can you put together a post with those two, the two 'Powered with' images (although I'd prefer it to say 'Built with'), and an icon?

**Comment by denis0706** [comment]
![redux4](https://f.cloud.github.com/assets/3092502/133216/6c14971e-70a2-11e2-93fa-358f14dbac40.jpg)

**Comment by evertiro** [comment]
Hmm... I'm sold on all but the icon. Can we put the 'x' part of the icon in a box (think checkbox)?

**Comment by ghost** [comment]
Those last ones are very cool!

**Comment by Pushplaybang** [comment]
nice.   - quite like the icon version actually, though out of all the option would vote for the flatter look (denis0706 options) without the gradients.

**Comment by evertiro** [comment]
@denis- I'm as sold as I'm gonna get on the logos themselves, can you provide the source files?

**Comment by denis0706** [comment]
there is only a bitmap sketchers, later I will prepare the source vector and good raster version

**Comment by denis0706** [comment]
[Redux Logo](http://wordpress-the.me/redux-logo.eps)
[Redux Icons](http://wordpress-the.me/redux-icons.zip)
![redux-logo](https://f.cloud.github.com/assets/3092502/156416/1f16be7a-7696-11e2-8933-f99db4bcb08d.jpg)

**Comment by evertiro** [comment]
That's a winner in my book! It'll start showing up in the next day or so...

**Comment by evertiro** [comment]
@denis0706 do you still have the eps files for these? I seem to have misplaced them...

**Comment by dennn** [comment]
Not sure why but I got an email notification for this. You might need to contact @denis0706 a different way.

**Comment by evertiro** [comment]
You got an email because you're a participant on the thread
