### ISSUE TITLE
Google webfonts preview not working

### ISSUE THREAD

**Issue by djevrek** [evertiro/historical-redux2#77]
Just to inform you that Google webfonts changes font in dropdown menu, but not on example below where it should (AFAIK). (i dont see where you trigger change on dropdown to also change font on .example class or maybe its just not working).

Also, maybe you should use this version of font.select https://github.com/hanoii/fontselect-jquery-plugin because have option for online getting latest list of google webfonts, and if its working offline, it have same list as your current plugin (its just updated fork).

**Comment by evertiro** [comment]
Nice catch! I'll update the plugin tonight.
