### ISSUE TITLE
Feature Request: Ability to reset tab-only to defaults

### ISSUE THREAD

**Issue by ghost** [evertiro/historical-redux2#78]
Feature request: Is it possible to have another "reset defaults" button, but only have it effect the current tab?

**Comment by evertiro** [comment]
What would the logic be behind that? What situation would that be important?

**Comment by ghost** [comment]
Well, for example I'm working on trying to create my own fieldset and am having a slow go at it. I needed to reset my values, but only for the fieldset I was working on. Sadly, the button reset everything (working as designed). Which got me thinking that I may not be the only one who would want to reset the values on the current page only, and not EVERYTHING. 

Just a thought.

**Comment by evertiro** [comment]
Hmmm interesting thought. Side note: May I ask what fieldset you're working on?

**Comment by ghost** [comment]
Having a go at issue #76  to see if I can merge multi_text with upload to create multi_upload. I'm not an expert, so it's not proving to be as easy as I thought, so I've been chipping away at it when spare time allows.

**Comment by dovy** [comment]
I doubt we'll ever do this. However, you can have a preset set with the new 3.0. Presets set any number of values in the panel and they're denoted by an image.

By doing this you could create your own "preset" to reset a small number of fields, or even a full tab.

All new with 3.0.

Will that work for you?
