### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by kouratoras** [evertiro/historical-redux2#79]
Hi!

I want to create an option for logo upload with option to remove it or change the image. I inesrt an upload filed in my sections array.

At first, the popup window was not even triggered when the button was pressed. The error was "formfield is not defined" and "previewis not defined". So i edited filed_upload.js file and added the lines

var formfield;
var preview;

The error was gone, but when i upload the image, it does not appear in the filed.

One more question.. is it possible to use the new media upload rather than the old that pops up now?

Thank you in advance.

**Comment by evertiro** [comment]
Confused... we have been using the new media upload for several versions now. Are you running the most recent release?

**Comment by kouratoras** [comment]
I updated to the latest version from github and everything is ok now. Maybe, the stable version zip at your site http://reduxframework.com/ is not updated?

**Comment by evertiro** [comment]
You're right, the stable link on the website was still pointing to the 1.0.0 release. Thanks for catching that!
