### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by deryckoe** [evertiro/historical-redux2#80]
Hi, I would like to create a translation .mo file for Redux. I could send to you, of course when I finish but I would like to know how can I translate Redux. the plugins generally comes with a languages folder and the related functions to load .mo files. Has Redux something like that?

Thanks in advance.

Best Regards.

**Comment by zenideas** [comment]
When you place this in your theme folder. Use the theme's textdomain in place of:
`define('Redux_TEXT_DOMAIN', 'redux-opts');`

Then generate your .po file using poEdit. 

The .po file would contain all the strings from the theme along with this Redux Framework.

**Comment by evertiro** [comment]
Hmm this should have been closed by now! Either way... feel free to submit translation files!
