### ISSUE TITLE
Creating on-page options for Custom Post Type

### ISSUE THREAD

**Issue by urbanimatic** [evertiro/historical-redux2#87]
Hi there,

I'm creating a plugin for creating Landing Pages.

I use a custom post type and custom fields for the landing pages content, but i need to add some on-page options for each entry. For example i need to have a an option(check box) for hiding the header(header is edited through a WYSIWYG custom field) on a specific landing page.

The examples as well as any tutorials i found online about creating settings/options pages are for general options but i need to have those options in the editing screen of my specific custom post type.

I'm not a PHP guru but i'm trying and willing to learn, any help will be appreciated or at least if someone can point me to the right direction it would be nice.

Cheers, 
Stelios

**Comment by psaikali** [comment]
To manage my theme custom post types and extra fields/metaboxes, I
personally use https://github.com/Gizburdt/Wordpress-Cuztom-Helper. You
should have a look, it does exactly what you're looking for!

**Comment by urbanimatic** [comment]
That's great, thanks for sharing. Based on your experience do you know if i can just use the meta boxes with the custom post type i have already created? Or i would have to do everything from scratch using Wordpress-Cuztom-Helper ?

**Comment by psaikali** [comment]
You will be able to assign metaboxes to the post type you already created, there is a parameter to define which post type(s) will receive the metaboxes.

**Comment by urbanimatic** [comment]
Thank you very much for everything!!!

**Comment by djevrek** [comment]
For me, best and most updated is https://github.com/rilwis/meta-box, and you're able to do what you imagine with this.

**Comment by urbanimatic** [comment]
Hi djevrek,

Thanks for sharing...have you ever tried integrating this with a plugin ?

**Comment by djevrek** [comment]
Its already plugin if you insert it in plugins directory. There is stable version here http://wordpress.org/extend/plugins/meta-box/ ...

**Comment by evertiro** [comment]
Closing as resolved
