### ISSUE TITLE
Serious memory usage problems

### ISSUE THREAD

**Issue by DanielBakovic** [evertiro/historical-redux2#90]
Hi,
I really like your framework and I was about to use it for my themes but then I saw that each time when WordPress loads all the arrays are initialized and populated with data that are only needed on the backend (section title, sub_desc, desc, options, std). That increases the memory usage and it can slow down sites.

For example these arrays are populated but not really needed on the frontend: $args, $sections and $tabs.

Could you please optimize the framework and load only data that are really needed.

Best regards,
Daniel

**Comment by denis0706** [comment]
Hi. 
I think we shouldn't load framework at frontend at all. 
But with current redux version we need redux get() method to get option value, because this is the only way to get new fields with std values.

**Comment by DanielBakovic** [comment]
Hi,
Maybe this could be solved when we check the theme version on init. For example when the theme version number isn't available in the database then the default settings should be loaded and added to the database. If there is already a older version in the database then an update function should be called to add new sections with default values. Then on the end of the update / install function there should be an action where we (developer) can hook into. For example do_action('Redux_after_setup') or something like that.

Best regards.
Daniel

**Comment by evertiro** [comment]
You're right that the framework shouldn't be loaded in the frontend... There's gotta be a simpler way to do it though.

**Comment by DanielBakovic** [comment]
Thx for the understanding :)

**Comment by denis0706** [comment]
Maybe just compare options from database with 'sections' array. 

``` php
            $fields = array();

            foreach ( $this->sections as $section )
                foreach ( $section['fields'] as $field )
                    $fields[$field['id']] = 1;

            $diff = array_diff_key ($fields, $this->options);
            if ( !empty( $diff ) )
              // update database
```

**Comment by DanielBakovic** [comment]
Hi,
when we can expect this fix?

**Comment by evertiro** [comment]
I'm still testing options, anyone who has a suggestion is more than welcome to bring it up, or even build it themselves and submit a pull request!

**Comment by asheborocreative** [comment]
If all you're trying to do is prevent loading it on the front end, just write an if statement around your require in the functions.php file that says:

if ( is_admin() ){
//require the page
}

It won't even try to load it anywhere but in the admin area. Your visitors could load every front end page without having the options framework try to load. Your stored options values would still be retrievable through the get_options function in WordPress.

**Comment by denis0706** [comment]
asheborocreative, agree with you, but your solution doens't work with current version of redux.
Currently default options set to db only once - [while there is no redux options at db](https://github.com/ghost1227/Redux-Framework/blob/master/options/defaults.php#L176-L186). So new options added after first redux options setting to db could be retrieved only with [get()](https://github.com/ghost1227/Redux-Framework/blob/master/options/defaults.php#L114-L123)   

So we need to rewrite some logic of framework. Now i don't think that we shouldn't load framework at front-end at all, but use some framework function to check if there are some new options at opitons.php, no matter where we - at the admin screen or at the front-end.

**Comment by evertiro** [comment]
I'm still researching this, but haven't found a safe simple way of doing this without completely rewriting the framework. Any suggestions would be welcome...

**Comment by DanielBakovic** [comment]
I've checked the code and I don't see other really elegant solution, too. It's the base design problem but maybe this could work:

Backend
1. Load framework files only on the backend (is_admin):
    1.1 setup_framework_options
    1.2 Redux_Options class
    1.3. maybe some other functions
2. On admin page check if default settings are already in the database. 
    2.1 If not, store all default options into the db.
    2.2 If there are already options available then add only options that are not in the db yet.

Frontend
1. On theme init, load options from the db into a global var: global $options; $options = get_option('opt_name')
2. Add a new function to theme-options.php to retrieve options from the options array like the "get" function from Redux_Options class. For example:
redux_get_option( option_name )

That will reduce the memory usage immensely.

**Comment by tridungpham** [comment]
how about : 
- Prepare a array to store default options (the default options array has same value as inside redux class, and is outside of redux class - another file for example, so we don't need to load redux file to get the default options)
- Only load Redux at backend. At frontend, load redux options, if redux options is null, we would use default options instead.

**Comment by dovy** [comment]
@DanielBakovic @denis0706 @asheborocreative @tridungpham 

With 3.0 I have reduced this dramatically. In the past, you were right. Things got loaded like mad. Let me give you an example:

I had a demo theme with 80 different options. I looked at the DB calls going on at each page load, **555**. INSANE!

I then optimised 3.0 a ton and I reduced that down to 30 on the options panel and even less on the front-end.

How's that? I think you'll be SUPER please.

Give 3.0 a try next week. I've optimised everything as far as it can go.
