### ISSUE TITLE
Themes Option Use Guide 

### ISSUE THREAD

**Issue by smtir** [evertiro/historical-redux2#93]
Hi, I'm low level wordpress user and i like your themes option framework. But i have problem that i can't use multiple check function , checkbox option and Checkbox to hide below. Please tell me how to use on my themes for those option?
Thanks

**Comment by evertiro** [comment]
I'm not sure I understand your question... Are you trying to figure out how to add them to the panel or use the variables once you have them?

**Comment by evertiro** [comment]
Just to keep everything in one place...

> Hi, I can't use checkbox option and Checkbox to hide below function on my themes. I don't know how to coding on my themes. Like this one "<?php echo $options['opt_ID']; ?>"
> If i use checkbox option and Checkbox to hide below then how to i code. I already create issue on wiki page. You may check it.
> 
> Thanks

**Comment by smtir** [comment]
if i try
 if ( isset($options['opt_ID'] ) ) {
   <?php echo $options['opt_ID']; ?>
}
for checkbox option and Checkbox to hide below then not working
also if i try
<?php
 if ( isset($options['opt_ID'] ) ) {
   <?php echo $options['opt_ID']; ?>
}
?>
then its not working. Now how to i code this  for this function(checkbox option and Checkbox to hide below)

**Comment by dovy** [comment]
This should be resolved in 3.0. Please give it a try next week and let me know if you face any issues.
