### ISSUE TITLE
Question: What is checkbox_hide_all ?

### ISSUE THREAD

**Issue by bluehiveinteractive** [evertiro/historical-redux2#94]
I saw in the change log that checkbox_hide_all was added in January. What is the purpose of this?

**Comment by KingYes** [comment]
You don't see `field_checkbox_hide_all.js` file?
https://github.com/ghost1227/Redux-Framework/blob/master/options/fields/checkbox_hide_all/field_checkbox_hide_all.js

**Comment by bhi-archive** [comment]
Yes. I did see that and under stand it hides the next item(s) after the chk box, but I am simply asking how to utilize this within the framework.

**Comment by evertiro** [comment]
Implement it the same way you would implement a checkbox. Instead of type => checkbox, just use checkbox_hide_all and it will hide everything from the checkbox to the next section head.
