### ISSUE TITLE
using options in a theme or plugin

### ISSUE THREAD

**Issue by hookedonweb** [evertiro/historical-redux2#95]
I have read over the documents on how to use the options but I don't understand it.

I am use to a conditional if with a get option .

Can someone show me how I can check if the option is set and then how to call it?

**Comment by tridungpham** [comment]
you can use the get_option function to retrieve the options array

``` php
$options = get_option(Redux_TEXT_DOMAIN)
if( isset( $options['your_option_id'] ) ) {
    //blah blah
}
```
