### ISSUE TITLE
HTML files in tabs - way to stop inserting breaks ?

### ISSUE THREAD

**Issue by bghouse** [evertiro/historical-redux2#97]
I'm using the Tabs array and including some html files as additional documentation. It seems like wpautop is firing here, as it's adding breaks everywhere unless I run the code all together.

Is there an easy way to stop that on these pages?

**Comment by evertiro** [comment]
It wouldn't shock me if it was... I honestly don't use it anymore since adding the raw HTML content type, but I'll take a look and see if we can make it bypass wpautop. We're doing it in a few other places, so shouldn't be too difficult.

**Comment by evertiro** [comment]
Closing to clean up the issue list. If you still want this, please feel free to let me know.
