### ISSUE TITLE
Reset Google Fonts

### ISSUE THREAD

**Issue by hirstmusic** [evertiro/historical-redux2#98]
I think it would be helpful if a user could un-select or reset the Google Font they've chosen. 

For instance, maybe they could go to the top of the list and choose "Select a font" or "None" so that no Google Font is applied.

I have a nice default font for a theme I'm creating, but I added the Google Font option through your framework so users could change it if they'd like. However, there's no way for them to revert to the default font without clicking "Reset to Defaults" which resets all options.

For now I have a note in the description area telling the user what the default Google font was. So it's not the end of the world... just might be a nice option.

Thanks for everything Ghost!

**Comment by evertiro** [comment]
Awesome idea! I'll add it soon.

**Comment by hirstmusic** [comment]
Fantastic :) Thanks for everything!

*Mike Hirst *
www.hirstmusic.com
